SELECT
    GRPC.id AS CARDTYPE_ID,
    GRPC.code AS CARDTYPE_CODE,
    GRPC.name AS CARDTYPE_NAME,
    GRPC.cardprefixbeg AS CARDTYPE_PREFIXBEGIN,
    GRPC.cardprefixend AS CARDTYPE_PREFIXEND
FROM
    GRPCCARD GRPC