SELECT FIRST(1)
(
    CASE
        WHEN (SELECT COUNT (DISTINCT COUNTERD.ID) FROM COUNTERD WHERE id > 0) > 0
            THEN (SELECT FIRST(1) id + 1 FROM COUNTERD WHERE id >= 0 ORDER BY id DESC)
            ELSE 1
    END
)
FROM
    COUNTERD